dir <- "/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/projects/emia/data/"
outputdir <- "/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/projects/emia/output/"

library(data.table)
library(JWileymisc)
library(extraoperators)
library(multilevelcoda)
library(multilevelTools)
library(emmeans)
library(doFuture)
library(compositions)
library(zCompositions)
library(bayestestR)
library(brms)
library(lme4)
library(loo)
library(performance)
library(ggplot2)
library(scales)
library(cowplot)
library(visreg)
library(ggthemes)
library(viridis)
library(tidyr)
library(gt)
library(gridExtra) 
library(ggpubr)
library(wesanderson)
library(hrbrthemes)
library(ggsci)
library(stats)
library(patchwork)
library(hrbrthemes)
library(latex2exp)
library(tvthemes)
library(stringr)
library(lubridate)
library(htmltools)
library(purrr)
library(abind)
library(dutchmasters)
library(haven)

expand.grid.df <- function(...) Reduce(function(...) merge.data.frame(..., by = NULL, all = TRUE), list(...))

scales::show_col(tvthemes:::hilda_palette$Day)
extrafont::loadfonts()


